{% set version = "2.0.15" %}

package:
  name: sdl2_ttf
  version: {{ version }}

source:
  url:  https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-{{ version }}.tar.gz
  sha256: a9eceb1ad88c1f1545cd7bd28e7cbc0b2c14191d40238f531a15b01b1b22cd33

build:
  number: 1

requirements:
  build:
    - cmake      # [win]
    - autoconf   # [unix]
    - automake   # [unix]
    - gnuconfig  # [unix]
    - libtool    # [unix]
    - make       # [unix]
    - {{ compiler('c') }}
  host:
    - sdl2 2.0.*
    - freetype
    # needed by freetype on linux...
    - zlib
  run:
    - sdl2 2.0.*
    - freetype

test:
  commands:
    - test -f $PREFIX/lib/libSDL2_ttf.a  # [unix]
    - test -f $PREFIX/lib/libSDL2_ttf.dylib  # [osx]
    - test -f $PREFIX/lib/libSDL2_ttf.so  # [linux]
    - test -f $PREFIX/include/SDL2/SDL_ttf.h  # [unix]
    - if not exist %LIBRARY_LIB%\\SDL2_ttf.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\SDL2_ttf.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\SDL2\\SDL_ttf.h exit 1  # [win]

about:
  home: https://github.com/libsdl-org/SDL_ttf
  license: Zlib
  license_file: COPYING.txt
  summary: "Library for using TrueType fonts in SDL applications"
  description: |
    Support for TrueType (.ttf) font files with Simple Directmedia Layer.
  doc_url: https://wiki.libsdl.org/SDL_ttf
  dev_url: https://github.com/libsdl-org/SDL_ttf

extra:
  recipe-maintainers:
    - h-vetinari
    - dschreij
