{% set version = "2.20.2" %}

package:
  name: sdl2_ttf
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/SDL_ttf/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 0fe9d587cdc4e6754b647536d0803bea8ca6ac77146c4209e0bed22391cf8241

build:
  number: 1
  run_exports:
    # see https://abi-laboratory.pro/tracker/timeline/sdl_ttf
    - {{ pin_subpackage("sdl2_ttf", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
    - sdl2
    - freetype
    - harfbuzz
    # needed by freetype on linux...
    - zlib       # [linux]

test:
  commands:
    # shared libs
    - test -f $PREFIX/lib/libSDL2_ttf.so                # [linux]
    - test -f $PREFIX/lib/libSDL2_ttf.dylib             # [osx]
    - if not exist %LIBRARY_LIB%\SDL2_ttf.lib exit 1    # [win]
    - if not exist %LIBRARY_BIN%\SDL2_ttf.dll exit 1    # [win]

    # absence of static libs
    - test ! -f $PREFIX/lib/libSDL2_ttf.a               # [unix]

    # headers
    - test -f $PREFIX/include/SDL2/SDL_ttf.h            # [unix]
    - if not exist %LIBRARY_INC%\SDL2\SDL_ttf.h exit 1  # [win]

about:
  home: https://github.com/libsdl-org/SDL_ttf
  license: Zlib
  license_file: LICENSE.txt
  summary: Library for using TrueType fonts in SDL applications
  description: |
    Support for TrueType (.ttf) font files with Simple Directmedia Layer.
  doc_url: https://wiki.libsdl.org/SDL_ttf
  dev_url: https://github.com/libsdl-org/SDL_ttf

extra:
  recipe-maintainers:
    - h-vetinari
    - dschreij
