# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "o3umMG/jphjG5H1a2rH5zI/7xj7lXtrdwef/z5EBPZV8KXfTxkGQ1MwDJrUnishxyS7YwvV+4B8SXH5Re5GqftR6Y6iNwZvIVEgqKCs5Ev4ak2dLkiMd36AsYTk/ghGagD86ZMkRM6M37F7U8S2X0hDKPYCSjeo/W6zLYfTtmuCcNXdHKMqiv+fvIVdh7FccLML62cYqOS2Hr9hcb4DgArVBk5GwclgKFXyg9nz5+2wzRPDvaknwFLLMkneNAfctF8jjgs/JhlF5fhGHG27JfF2tZndaT7pPYxlsRpYOfuryR68SI0ufnCbyvtQnuxIWGw5z9Skl1mQR6JJWd6NlbOYR1H8+/WKZQmLLA1fV+G4Itgjc4Bpo3PCjrsi8aOZD8tsp6B9yLzeBQcsICrdy4fRZK3LD6bKX1YZymDFqYm3+Z64p6jFzhMeQXlsVqZ/8GXmXSFcOdMaP1jMteASh2VL5VYx3lzJ2nyCmNhOHpbgTBT9n7vCi/j5da+H41rBaxO9zt1z3Segnxcsu10wFxvZLy7wvgV1Rw7FgkazqUjZqXg18FeA8LGSZlgWqK619N2BEr+V+QRNYRAuS0j2N8t2LKFKxNwVdw8kgz2GMVd38tjyRHDH7lKA5VKAZWaZgG9oyKI4WqtNzjikWP9GrM1YRXO8VC/kWolBnSDggd1w="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
