appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: o3umMG/jphjG5H1a2rH5zI/7xj7lXtrdwef/z5EBPZV8KXfTxkGQ1MwDJrUnishxyS7YwvV+4B8SXH5Re5GqftR6Y6iNwZvIVEgqKCs5Ev4ak2dLkiMd36AsYTk/ghGagD86ZMkRM6M37F7U8S2X0hDKPYCSjeo/W6zLYfTtmuCcNXdHKMqiv+fvIVdh7FccLML62cYqOS2Hr9hcb4DgArVBk5GwclgKFXyg9nz5+2wzRPDvaknwFLLMkneNAfctF8jjgs/JhlF5fhGHG27JfF2tZndaT7pPYxlsRpYOfuryR68SI0ufnCbyvtQnuxIWGw5z9Skl1mQR6JJWd6NlbOYR1H8+/WKZQmLLA1fV+G4Itgjc4Bpo3PCjrsi8aOZD8tsp6B9yLzeBQcsICrdy4fRZK3LD6bKX1YZymDFqYm3+Z64p6jFzhMeQXlsVqZ/8GXmXSFcOdMaP1jMteASh2VL5VYx3lzJ2nyCmNhOHpbgTBT9n7vCi/j5da+H41rBaxO9zt1z3Segnxcsu10wFxvZLy7wvgV1Rw7FgkazqUjZqXg18FeA8LGSZlgWqK619N2BEr+V+QRNYRAuS0j2N8t2LKFKxNwVdw8kgz2GMVd38tjyRHDH7lKA5VKAZWaZgG9oyKI4WqtNzjikWP9GrM1YRXO8VC/kWolBnSDggd1w=}
